Create 1D array of numbers from 1 to 10.
Reshape it into 2D array with dimensions 2*5
Create a 2D array, Calculate and print sum,mean, std, min max of the array.

In [51]:
import numpy as np
arr=np.arange(1,11)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [53]:
arr.reshape(2,5)

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [59]:
mean = np.mean(arr)
mean

5.5

In [61]:
median=np.median(arr)
median

5.5

In [65]:
sum=np.sum(arr)
sum

55

In [69]:
std_dev=np.std(arr)
std_dev

2.8722813232690143

In [72]:
minimum=np.min(arr)
minimum

1

In [76]:
maximum=np.max(arr)
maximum

10

In [1]:
lst = [[7, 92, 95, 32, 11, 89, 41, 4, 45, 3, 17, 17, 47, 40, 4, 80, 10, 49, 73, 95, 24, 5, 67, 8, 14, 51, 39, 48, 57, 100, 89, 32, 68, 23]]
print(type(lst))
shape = len(lst)
print(shape)
lst1 = [x**2 for x in lst[0]]
print(lst1)

import numpy as np
arr1=np.array(lst)
print(arr1)
arr1.shape
arr1.dtype
arr1*arr1

<class 'list'>
1
[49, 8464, 9025, 1024, 121, 7921, 1681, 16, 2025, 9, 289, 289, 2209, 1600, 16, 6400, 100, 2401, 5329, 9025, 576, 25, 4489, 64, 196, 2601, 1521, 2304, 3249, 10000, 7921, 1024, 4624, 529]
[[  7  92  95  32  11  89  41   4  45   3  17  17  47  40   4  80  10  49
   73  95  24   5  67   8  14  51  39  48  57 100  89  32  68  23]]


array([[   49,  8464,  9025,  1024,   121,  7921,  1681,    16,  2025,
            9,   289,   289,  2209,  1600,    16,  6400,   100,  2401,
         5329,  9025,   576,    25,  4489,    64,   196,  2601,  1521,
         2304,  3249, 10000,  7921,  1024,  4624,   529]])

In [3]:
import numpy as np
arr2=np.array([1,2,3,4,5,6,7,8,9,10])
arr3=arr2.reshape(2,5)
print(arr3)
print(arr3[0:1])
print(arr3.mean())
print(arr3.sum())
print(arr3.std())

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
[[1 2 3 4 5]]
5.5
55
2.8722813232690143


In [5]:
import pandas as pd
data = {
    'Name': ['Alice', 'Bob', 'Carol', 'Dave'],
    'Age': [20, 22, 19, 21],
    'Gender': ['F', 'M', 'F', 'M'],
    'City': ['New York', 'Boston', 'Chicago', 'Seattle'],
    'Marks': [85, 90, 78, 88]
}

df = pd.DataFrame(data)

print(df)

    Name  Age Gender      City  Marks
0  Alice   20      F  New York     85
1    Bob   22      M    Boston     90
2  Carol   19      F   Chicago     78
3   Dave   21      M   Seattle     88
